openapi: 3.0.3
info:
  title: Vehicle Management Services (app)
  description: Vehicle Management Services (app)
  version: 1.0.0
paths:
  /vehicle-management/v1/trucks:
    get:
      operationId: listTrucks
      summary: List Trucks.
      description: Lists Trucks.
      tags:
        - Trucks
      parameters:
        - name: plateNumber
          in: query
          description: Filter results by plate number
          schema:
            type: string
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of trucks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Truck"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/trucks/{truckId}:
    get:
      operationId: findTruck
      summary: Find a truck.
      description: Finds a truck by id.
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: trucks id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found truck
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Truck"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/trailers:
    get:
      operationId: listTrailers
      summary: List Trailers.
      description: Lists Trailers.
      tags:
        - Trailers
      parameters:
        - name: plateNumber
          in: query
          description: Filter results by plate number
          schema:
            type: string
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of trailers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Trailer"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/trailers/{trailerId}:
    get:
      operationId: findTrailer
      summary: Find a trailer.
      description: Finds a trailer by id.
      tags:
        - Trailers
      parameters:
        - name: trailerId
          required: true
          in: path
          description: trailers id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found trailer
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trailer"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/vehicles:
    get:
      operationId: listVehicles
      summary: List Vehicles.
      description: Lists Vehicles.
      tags:
        - Vehicles
      parameters:
        - name: truckId
          in: query
          description: Filter results by truck id
          schema:
            type: string
            format: uuid
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of vehicles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Vehicle"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/vehicles/{vehicleId}:
    get:
      operationId: findVehicle
      summary: Find a vehicle.
      description: Finds a vehicle by id.
      tags:
        - Vehicles
      parameters:
        - name: vehicleId
          required: true
          in: path
          description: vehicles id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found vehicle
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Vehicle"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /work-planning/v1/routes:
    get:
      operationId: listRoutes
      summary: List Routes.
      description: Lists Routes.
      tags:
        - Routes
      parameters:
        - name: vehicleId
          in: query
          description: Filter results by vehicle id
          schema:
            type: string
            format: uuid
        - name: driverId
          in: query
          description: Filter results by driver id
          schema:
            type: string
            format: uuid
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Route"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /work-planning/v1/routes/{routeId}:
    get:
      operationId: findRoute
      summary: Find a route.
      description: Finds a route by id.
      tags:
        - Routes
      parameters:
        - name: routeId
          required: true
          in: path
          description: routes id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found route
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Route"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    Truck:
      type: object
      description: Represent single truck
      required:
        - plateNumber
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        plateNumber:
          type: string
        vin:
          type: string
          description: Truck identification number. This is unique for each truck and
            should be used as a hardware identifier for this specific truck
    Trailer:
      type: object
      description: Represent single trailer
      required:
        - plateNumber
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        plateNumber:
          type: string
        vin:
          type: string
          description: Trailer identification number. This is unique for each trailer and
            should be used as a hardware identifier for this specific trailer
    Vehicle:
      type: object
      description: Represent single vehicle
      required:
        - truckId
        - trailerIds
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        truckId:
          type: string
          description: Truck that towing the vehicle
          format: uuid
        trailerIds:
          type: array
          description: >
            List of attached trailers to vehicle. Order of trailers should
            reflect the order of trailers in the vehicle where first trailer is
            the closest to the truck.
          minItems: 0
          maxItems: 2
          items:
            type: string
            format: uuid
    Route:
      type: object
      description: Represent single planned route for single truck driver
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        vehicleId:
          type: string
          format: uuid
          description: Vehicle id
        driverId:
          type: string
          format: uuid
          description: Driver id
