openapi: 3.0.3
info:
  title: Vehicle Management Services (auth)
  description: Vehicle Management Services (auth)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/trucks/{truckId}/driverCards:
    get:
      operationId: listTruckDriverCards
      summary: Lists truck driver cards
      description: Lists truck driver cards. Used to check if a truck has a driver
        card inserted.
      security:
        - ApiKeyAuth: []
        - BearerAuth:
            - driver
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: truck ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of truck driver cards. Contains either 0 or 1 cards.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TruckDriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user-management/v1/clientApps/{clientAppId}:
    get:
      operationId: findClientApp
      summary: Find a client app.
      description: Finds a client app by ID.
      security:
        - BearerAuth:
            - manager
        - ApiKeyAuth: []
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: client app's ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateClientApp
      summary: Update a client app.
      description: Updates a client app.
      security:
        - BearerAuth:
            - manager
        - ApiKeyAuth: []
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: Client app's ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientApp"
      responses:
        "200":
          description: Updated client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    TruckSortByField:
      type: string
      enum:
        - NAME
        - PLATE_NUMBER
    SortOrder:
      type: string
      enum:
        - ASCENDING
        - DESCENDING
    TruckDriverCard:
      type: object
      required:
        - id
        - timestamp
      properties:
        id:
          type: string
          description: Driver card ID
        timestamp:
          type: integer
          format: int64
          description: Timestamp for driver card insertion. Unix timestamp in milliseconds.
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    TruckDriveStateEnum:
      type: string
      enum:
        - REST
        - DRIVER_AVAILABLE
        - WORK
        - DRIVE
        - ERROR
        - NOT_AVAILABLE
    SalaryGroup:
      type: string
      description: >
        Employee's salary group

        Kuljettaja (Driver) - Should be default IF the employees office is not KOTKA

        VP-Logistics (VPlogistics)

        Office

        Terminal
      enum:
        - DRIVER
        - VPLOGISTICS
        - OFFICE
        - TERMINAL
    EmployeeType:
      type: string
      description: >
        Employee's type described as finnish abbreviation. UI implementations
        should translate these to more human readable form.

        Pakettiautonkuljettaja (PA)

        Kuorma-auton kuljettaja (KA)

        Alihankkija (AH)

        Vuokratyöntekijä (VK)

        Työharjoittelija (TH)

        Tilapäistyöntekijä (TP)

        Ajojärjestelijä (AJ)

        Esimies (JH)

        Aikatuntipalkka (AP)

        Kuukausipalkka (KK)

        Ei-aktiivinen (POIS)

        Täysperäkuljettaja (TPK)
      enum:
        - PA
        - KA
        - AH
        - VK
        - TH
        - TP
        - AJ
        - JH
        - AP
        - KK
        - POIS
        - TPK
    Office:
      type: string
      description: Employee's office. Salary group should be set to VPLogistics if the
        office is KOTKA
      enum:
        - KOTKA
        - KOUVOLA
        - RAUHA
    WorkEventType:
      type: string
      description: >
        Work event types. UI implementations should translate these to more
        human readable form.


        *Office/Terminal work types*

        - VEGETABLE (Hevi)

        - DRY (Kuiva)

        - MEAT_CELLAR (Lihakellari)

        - MEIRA (Meira)

        - FROZEN (Pakaste)

        - PALTE (Palte)

        - BREWERY (Panimo)

        - GREASE (Rasva)

        - LOGIN

        - LOGOUT


        *Common work types*

        - OTHER_WORK (Muu työ)

        - BREAK (Tauko)

        - SHIFT_START

        - SHIFT_END

        - UNKNOWN


        *Driver work types*

        - DRIVE

        - LOADING

        - UNLOADING

        - AVAILABILITY

        - DRIVER_CARD_INSERTED

        - DRIVER_CARD_REMOVED
      enum:
        - VEGETABLE
        - DRY
        - MEAT_CELLAR
        - MEIRA
        - FROZEN
        - PALTE
        - BREWERY
        - GREASE
        - LOGIN
        - LOGOUT
        - OTHER_WORK
        - BREAK
        - SHIFT_START
        - SHIFT_END
        - UNKNOWN
        - DRIVE
        - LOADING
        - UNLOADING
        - AVAILABILITY
        - DRIVER_CARD_INSERTED
        - DRIVER_CARD_REMOVED
    ClientAppStatus:
      type: string
      description: Client app status
      enum:
        - PENDING
        - APPROVED
        - EXPIRED
    ClientApp:
      type: object
      description: >
        Represents single client app.


        Client apps are created when a new client app publishes itself to the system. Apps will be in PENDING status

        until a manager approves them. Three months after its approval a client app will change to EXPIRED status.

        The app will then need to be approved again by a manager.


        The device ID of the client app is used together with user PIN code during authentication.
      required:
        - deviceId
        - status
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        deviceId:
          type: string
          description: Device ID
        name:
          type: string
          description: Device name
        status:
          $ref: "#/components/schemas/ClientAppStatus"
        metadata:
          type: object
          description: client app metadata, e.g. device OS, device OS version, app version
          additionalProperties:
            type: string
        lastLoginAt:
          type: string
          format: date-time
          description: Last time the client app has logged in to the system
        createdAt:
          type: string
          format: date-time
          description: Creation time
        lastModifierId:
          type: string
          format: uuid
          description: Last modifier's ID
        modifiedAt:
          type: string
          format: date-time
          description: Last modified time
    TaskType:
      type: string
      description: Type of the task
      enum:
        - UNLOAD
        - LOAD
