openapi: 3.0.3
info:
  title: Vehicle Management Services (auth)
  description: Vehicle Management Services (auth)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/trucks/{truckId}/driverCards:
    get:
      operationId: listTruckDriverCards
      summary: Lists truck driver cards
      description: Lists truck driver cards. Used to check if a truck has a driver
        card inserted.
      security:
        - ApiKeyAuth: []
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: truck ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of truck driver cards. Contains either 0 or 1 cards.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TruckDriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    TruckSortByField:
      type: string
      enum:
        - NAME
        - PLATE_NUMBER
    SortOrder:
      type: string
      enum:
        - ASCENDING
        - DESCENDING
    TruckDriverCard:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Driver card ID
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    TruckDriveStateEnum:
      type: string
      enum:
        - REST
        - DRIVER_AVAILABLE
        - WORK
        - DRIVE
        - ERROR
        - NOT_AVAILABLE
    TaskType:
      type: string
      description: Type of the task
      enum:
        - UNLOAD
        - LOAD
