openapi: 3.0.3
info:
  title: Vehicle Management Services (auth)
  description: Vehicle Management Services (auth)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /v1/trucks/{truckId}/driverCards:
    get:
      operationId: listTruckDriverCards
      summary: Lists truck driver cards
      description: Lists truck driver cards. Used to check if a truck has a driver
        card inserted.
      security: []
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: truck ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of truck driver cards. Contains either 0 or 1 cards.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TruckDriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/clientApps/{clientAppId}:
    get:
      operationId: findClientApp
      summary: Find a client app.
      description: Finds a client app by ID.
      security: []
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: client app's ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateClientApp
      summary: Update a client app.
      description: Updates a client app.
      security: []
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: Client app's ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientApp"
      responses:
        "200":
          description: Updated client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/verifyClientApp:
    post:
      operationId: verifyClientApp
      summary: Verifies that the client app has been approved.
      description: Verifies that the client app has been approved.
      security: []
      tags:
        - ClientApps
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyClientAppRequest"
      responses:
        "200":
          description: Whether client app is approved or not
          content:
            application/json:
              schema:
                type: boolean
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    TruckDriverCard:
      type: object
      required:
        - id
        - timestamp
      properties:
        id:
          type: string
          description: Driver card ID
        timestamp:
          type: integer
          format: int64
          description: Timestamp for driver card insertion. Unix timestamp in milliseconds.
        removedAt:
          type: string
          format: date-time
          description: Removed at. Used to check for grace period for driver card removal.
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    ClientApp:
      type: object
      description: >
        Represents single client app.


        Client apps are created when a new client app publishes itself to the system. Apps will be in

        WAITING_FOR_APPROVAL status until a manager approves them. Three months after its approval a client app will

        again change to WAITING_FOR_APPROVAL status. The app will then need to be approved again by a manager.


        The device ID of the client app is used together with user PIN code during authentication.
      required:
        - deviceId
        - status
        - metadata
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        deviceId:
          type: string
          description: Device ID
        name:
          type: string
          description: Device name
        status:
          $ref: "#/components/schemas/ClientAppStatus"
        metadata:
          $ref: "#/components/schemas/ClientAppMetadata"
        lastLoginAt:
          type: string
          format: date-time
          description: Last time the client app has logged in to the system
        createdAt:
          type: string
          format: date-time
          description: Creation time
        lastModifierId:
          type: string
          format: uuid
          description: Last modifier's ID
        modifiedAt:
          type: string
          format: date-time
          description: Last modified time
    VerifyClientAppRequest:
      type: object
      properties:
        deviceId:
          type: string
          description: device ID
    ClientAppStatus:
      type: string
      description: Client app status
      enum:
        - WAITING_FOR_APPROVAL
        - APPROVED
    ClientAppMetadata:
      type: object
      description: Client app metadata
      properties:
        deviceOS:
          type: string
          description: Device OS
          enum:
            - ANDROID
        deviceOSVersion:
          type: string
          description: Device OS version
        appVersion:
          type: string
          description: App version
