openapi: 3.0.3
info:
  title: Vehicle Management Services (auth)
  description: Vehicle Management Services (auth)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/trucks/{truckId}/driverCards:
    get:
      operationId: listTruckDriverCards
      summary: Lists truck driver cards
      description: Lists truck driver cards. Used to check if a truck has a driver
        card inserted.
      security:
        - ApiKeyAuth: []
        - BearerAuth:
            - driver
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: truck ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of truck driver cards. Contains either 0 or 1 cards.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TruckDriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /user-management/v1/clientApps/{clientAppId}:
    get:
      operationId: findClientApp
      summary: Find a client app.
      description: Finds a client app by ID.
      security:
        - BearerAuth:
            - manager
        - ApiKeyAuth: []
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: client app's ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateClientApp
      summary: Update a client app.
      description: Updates a client app.
      security:
        - BearerAuth:
            - manager
      tags:
        - ClientApps
      parameters:
        - name: clientAppId
          required: true
          in: path
          description: Client app's ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClientApp"
      responses:
        "200":
          description: Updated client app
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientApp"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    TruckSortByField:
      type: string
      enum:
        - NAME
        - PLATE_NUMBER
    SortOrder:
      type: string
      enum:
        - ASCENDING
        - DESCENDING
    TruckDriverCard:
      type: object
      required:
        - id
        - timestamp
      properties:
        id:
          type: string
          description: Driver card ID
        timestamp:
          type: integer
          format: int64
          description: Timestamp for driver card insertion. Unix timestamp in milliseconds.
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    TruckDriveStateEnum:
      type: string
      enum:
        - REST
        - DRIVER_AVAILABLE
        - WORK
        - DRIVE
        - ERROR
        - NOT_AVAILABLE
    SalaryGroup:
      type: string
      description: >
        Employee's salary group

        Kuljettaja (Driver) - Should be default IF the employees office is not KOTKA

        VP-Logistics (VPlogistics)

        Office

        Terminal
      enum:
        - DRIVER
        - VPLOGISTICS
        - OFFICE
        - TERMINAL
    EmployeeType:
      type: string
      enum:
        - PA
        - KA
        - AH
        - VK
        - TH
        - TP
        - AJ
        - JH
        - AP
        - KK
        - POIS
        - TPK
      description: >
        Employee's type described as finnish abbreviation. UI implementations
        should translate these to more human readable form.


        | Abbreviation | finnish name            |

        | ------------ | ----------------------- |

        | PA           | Pakettiautonkuljettaja  |

        | KA           | Kuorma-auton kuljettaja |

        | AH           | Alihankkija             |

        | VK           | Vuokratyöntekijä        |

        | TH           | Työharjoittelija        |

        | TP           | Tilapäistyöntekijä      |

        | AJ           | Ajojärjestelijä         |

        | JH           | Esimies                 |

        | AP           | Aikatuntipalkka         |

        | KK           | Kuukausipalkka          |

        | POIS         | Ei-aktiivinen           |

        | TPK          | Täysperäkuljettaja      |
    Office:
      type: string
      description: Employee's office. Salary group should be set to VPLogistics if the
        office is KOTKA
      enum:
        - KOTKA
        - KOUVOLA
        - RAUHA
    WorkType:
      type: string
      description: >
        Work type of the work shift hours. A single work type represents
        aggregated value from

        one or more work event types.


        | name                   | finnish name         |

        | ---------------------- | -------------------- |

        | PAID_WORK              | Palkallinen työ      |

        | BREAK                  | Tauko                |

        | STANDBY                | Odotus               |

        | EVENING_ALLOWANCE      | Iltatyö              |

        | NIGHT_ALLOWANCE        | Yötyö                |

        | HOLIDAY_ALLOWANCE      | Pyhälisä             |

        | JOB_SPECIFIC_ALLOWANCE | Työkohtaisuuslisä    |

        | FROZEN_ALLOWANCE       | Pakastelisä          |
      enum:
        - PAID_WORK
        - BREAK
        - STANDBY
        - EVENING_ALLOWANCE
        - NIGHT_ALLOWANCE
        - HOLIDAY_ALLOWANCE
        - JOB_SPECIFIC_ALLOWANCE
        - FROZEN_ALLOWANCE
    ClientAppStatus:
      type: string
      description: Client app status
      enum:
        - WAITING_FOR_APPROVAL
        - APPROVED
    ClientApp:
      type: object
      description: >
        Represents single client app.


        Client apps are created when a new client app publishes itself to the system. Apps will be in

        WAITING_FOR_APPROVAL status until a manager approves them. Three months after its approval a client app will

        again change to WAITING_FOR_APPROVAL status. The app will then need to be approved again by a manager.


        The device ID of the client app is used together with user PIN code during authentication.
      required:
        - deviceId
        - status
        - metadata
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        deviceId:
          type: string
          description: Device ID
        name:
          type: string
          description: Device name
        status:
          $ref: "#/components/schemas/ClientAppStatus"
        metadata:
          $ref: "#/components/schemas/ClientAppMetadata"
        lastLoginAt:
          type: string
          format: date-time
          description: Last time the client app has logged in to the system
        createdAt:
          type: string
          format: date-time
          description: Creation time
        lastModifierId:
          type: string
          format: uuid
          description: Last modifier's ID
        modifiedAt:
          type: string
          format: date-time
          description: Last modified time
    ClientAppMetadata:
      type: object
      description: Client app metadata
      properties:
        deviceOS:
          type: string
          description: Device OS
          enum:
            - ANDROID
        deviceOSVersion:
          type: string
          description: Device OS version
        appVersion:
          type: string
          description: App version
    TaskType:
      type: string
      description: Type of the task
      enum:
        - UNLOAD
        - LOAD
