openapi: 3.0.3
info:
  title: Vehicle Management Services (auth)
  description: Vehicle Management Services (auth)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/driverCard/{vin}:
    get:
      operationId: getCurrentDriverCardInTruck
      summary: Returns current driver card in truck
      description: Returns current driver card in truck, or null if no card is inserted.
      security:
        - ApiKeyAuth: []
      tags:
        - DriverCard
      parameters:
        - name: vin
          required: true
          in: path
          description: Vehicle identification number
          schema:
            type: string
      responses:
        "200":
          description: Driver card currently inserted in truck
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    DriverCard:
      type: object
      properties:
        driverCardId:
          type: string
          nullable: true
          description: Driver card ID
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
