openapi: 3.0.3
info:
  title: Vehicle Management Services (full)
  description: Vehicle Management Services (full)
  version: 1.0.0
paths:
  /v1/trucks:
    get:
      operationId: listTrucks
      summary: List Trucks.
      description: Lists Trucks.
      tags:
        - Trucks
        - SpecApp
        - SpecManagementUI
        - SpecExternal
      parameters:
        - name: plateNumber
          in: query
          description: Filter results by plate number
          schema:
            type: string
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of trucks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Truck"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/trucks/{truckId}:
    get:
      operationId: findTruck
      summary: Find a truck.
      description: Finds a truck by id.
      tags:
        - Trucks
        - SpecApp
        - SpecManagementUI
        - SpecExternal
      parameters:
        - name: truckId
          required: true
          in: path
          description: trucks id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found truck
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Truck"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/routes:
    get:
      operationId: listRoutes
      summary: List Routes.
      description: Lists Routes.
      tags:
        - Routes
        - SpecManagementUI
        - SpecApp
        - SpecExternal
      parameters:
        - name: vehicleId
          in: query
          description: Filter results by vehicle id
          schema:
            type: string
            format: uuid
        - name: driverId
          in: query
          description: Filter results by driver id
          schema:
            type: string
            format: uuid
        - name: first
          in: query
          description: First result.
          schema:
            type: integer
        - name: max
          in: query
          description: Max results.
          schema:
            type: integer
      responses:
        "200":
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Route"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /v1/routes/{routeId}:
    get:
      operationId: findRoute
      summary: Find a route.
      description: Finds a route by id.
      tags:
        - Routes
        - SpecApp
        - SpecManagementUI
        - SpecExternal
      parameters:
        - name: routeId
          required: true
          in: path
          description: routes id
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Found route
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Route"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    Truck:
      type: object
      description: Represent single truck
      required:
        - plateNumber
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        plateNumber:
          type: string
    Route:
      type: object
      description: Represent single planned route for single truck driver
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        vehicleId:
          type: string
          format: uuid
          description: Vehicle id
        driverId:
          type: string
          format: uuid
          description: Driver id
