openapi: 3.0.3
info:
  title: Vehicle Management Services (vehicle-data-receiver)
  description: Vehicle Management Services (vehicle-data-receiver)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/driverCards/{driverCardId}:
    put:
      operationId: updateDriverCard
      summary: Updates driver cards
      description: Updates single driver card.
      security:
        - ApiKeyAuth: []
      tags:
        - DriverCards
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverCard"
        description: Payload
        required: true
      parameters:
        - name: driverCardId
          required: true
          in: path
          description: driver card ID
          schema:
            type: string
      responses:
        "200":
          description: Updated driver card
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    DriverCard:
      type: object
      required:
        - driverCardId
        - truckVin
      properties:
        driverCardId:
          type: string
          description: Driver card ID
        truckVin:
          type: string
          nullable: true
          description: Truck's vehicle identification number
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
