openapi: 3.0.3
info:
  title: Vehicle Management Services (vehicle-data-receiver)
  description: Vehicle Management Services (vehicle-data-receiver)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/driverCards/{driverCardId}:
    put:
      operationId: updateDriverCard
      summary: Updates driver cards
      description: Updates single driver card.
      security:
        - ApiKeyAuth: []
      tags:
        - DriverCards
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverCard"
        description: Payload
        required: true
      parameters:
        - name: driverCardId
          required: true
          in: path
          description: driver card ID
          schema:
            type: string
      responses:
        "200":
          description: Updated driver card
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DriverCard"
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/trucks/{truckId}/locations:
    post:
      operationId: createTruckLocation
      summary: Create truck location
      description: Create new truck location. Used by vehicle data receiver to send
        truck location data.
      security:
        - ApiKeyAuth: []
      tags:
        - Trucks
      parameters:
        - name: truckId
          required: true
          in: path
          description: truck id
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TruckLocation"
        description: Payload
        required: true
      responses:
        "201":
          description: Received data
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/telematics/{vin}:
    post:
      operationId: receiveTelematicData
      summary: Receives telematic data entry
      description: Receives telematic data entry
      security:
        - ApiKeyAuth: []
      tags:
        - Telematics
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TelematicData"
        description: Payload
        required: true
      parameters:
        - name: vin
          required: true
          in: path
          description: Truck or towable vehicle identification number
          schema:
            type: string
      responses:
        "204":
          description: Success
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    DriverCard:
      type: object
      required:
        - driverCardId
        - truckVin
      properties:
        driverCardId:
          type: string
          description: Driver card ID
        truckVin:
          type: string
          nullable: true
          description: Truck's vehicle identification number
    Error:
      type: object
      description: Error object
      required:
        - status
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
    TruckLocation:
      type: object
      required:
        - id
        - latitude
        - longitude
        - heading
      properties:
        id:
          type: integer
          format: int64
          description: Timestamp for truck speed
        latitude:
          type: number
          format: double
          description: Latitude in degrees.
        longitude:
          type: number
          format: double
          description: Longitude in degrees.
        heading:
          type: number
          format: double
          description: heading in degrees.
    TelematicData:
      type: object
      required:
        - timestamp
        - imei
        - speed
        - latitude
        - longitude
      properties:
        timestamp:
          type: integer
          format: int64
        imei:
          type: string
        speed:
          type: number
          format: float
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
