openapi: 3.0.3
info:
  title: Vehicle Management Services (vehicle-data-receiver)
  description: Vehicle Management Services (vehicle-data-receiver)
  version: 1.0.0
security:
  - ApiKeyAuth: []
paths:
  /vehicle-management/v1/telematics/{vin}:
    post:
      operationId: receiveTelematicData
      summary: Receives telematic data entry
      description: Receives telematic data entry
      security:
        - ApiKeyAuth: []
      tags:
        - Telematics
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TelematicData"
        description: Payload
        required: true
      parameters:
        - name: vin
          required: true
          in: path
          description: Truck or towable vehicle identification number
          schema:
            type: string
      responses:
        "204":
          description: Success
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /vehicle-management/v1/telematics/{vin}/driverCard:
    post:
      operationId: receiveDriverCardEvent
      summary: Receives driver card events
      description: >
        Receives driver card events. Truck will be identified via VIN in the
        path. Events are sent when card is inserted to a vehicle and when
        removed from it. When card is inserted, driverCardId value should be the
        ID of the card. When card is removed, driverCardId value should be null.
      security:
        - ApiKeyAuth: []
      tags:
        - Telematics
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverCard"
        description: Payload
        required: true
      parameters:
        - name: vin
          required: true
          in: path
          description: Truck or towable vehicle identification number
          schema:
            type: string
      responses:
        "204":
          description: Success
        default:
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        status:
          type: integer
          format: int32
        message:
          type: string
        creatorId:
          type: string
          readOnly: true
          format: uuid
        createdAt:
          format: date-time
          type: string
          readOnly: true
        lastModifierId:
          type: string
          readOnly: true
          format: uuid
        modifiedAt:
          format: date-time
          type: string
          readOnly: true
    TelematicData:
      type: object
      required:
        - timestamp
        - imei
        - speed
        - latitude
        - longitude
      properties:
        timestamp:
          type: integer
          format: int64
        imei:
          type: string
        speed:
          type: number
          format: float
        latitude:
          type: number
          format: double
        longitude:
          type: number
          format: double
    DriverCard:
      type: object
      properties:
        driverCardId:
          type: string
          nullable: true
          description: Driver card ID
